// <auto-generated>
//     Generated by tools\gen-strings.ps1 from Strings.resx. Do not edit by hand.
// </auto-generated>

#nullable enable

using System.Globalization;
using System.Resources;

namespace iPrtSc.Resources;

/// <summary>Strongly-typed access to the UI strings (Strings.resx + per-culture Strings.xx.resx).</summary>
public static class Strings
{
    private static readonly ResourceManager Manager =
        new("iPrtSc.Resources.Strings", typeof(Strings).Assembly);

    /// <summary>Overrides the culture used for lookups; null follows CurrentUICulture.</summary>
    public static CultureInfo? Culture { get; set; }

    /// <summary>Cancel</summary>
    public static string Common_Cancel => Manager.GetString("Common_Cancel", Culture) ?? "Common_Cancel";

    /// <summary>Save</summary>
    public static string Common_Save => Manager.GetString("Common_Save", Culture) ?? "Common_Save";

    /// <summary>Copy</summary>
    public static string Common_Copy => Manager.GetString("Common_Copy", Culture) ?? "Common_Copy";

    /// <summary>Cut</summary>
    public static string Common_Cut => Manager.GetString("Common_Cut", Culture) ?? "Common_Cut";

    /// <summary>Paste</summary>
    public static string Common_Paste => Manager.GetString("Common_Paste", Culture) ?? "Common_Paste";

    /// <summary>Select all</summary>
    public static string Common_SelectAll => Manager.GetString("Common_SelectAll", Culture) ?? "Common_SelectAll";

    /// <summary>None</summary>
    public static string Common_None => Manager.GetString("Common_None", Culture) ?? "Common_None";

    /// <summary>Ctrl</summary>
    public static string Common_KeyCtrl => Manager.GetString("Common_KeyCtrl", Culture) ?? "Common_KeyCtrl";

    /// <summary>Esc</summary>
    public static string Common_KeyEsc => Manager.GetString("Common_KeyEsc", Culture) ?? "Common_KeyEsc";

    /// <summary>Enter</summary>
    public static string Common_KeyEnter => Manager.GetString("Common_KeyEnter", Culture) ?? "Common_KeyEnter";

    /// <summary>iPrtSc Settings</summary>
    public static string Settings_WindowTitle => Manager.GetString("Settings_WindowTitle", Culture) ?? "Settings_WindowTitle";

    /// <summary>Settings</summary>
    public static string Settings_Header => Manager.GetString("Settings_Header", Culture) ?? "Settings_Header";

    /// <summary>Hotkeys</summary>
    public static string Settings_Nav_Hotkeys => Manager.GetString("Settings_Nav_Hotkeys", Culture) ?? "Settings_Nav_Hotkeys";

    /// <summary>Saving</summary>
    public static string Settings_Nav_Saving => Manager.GetString("Settings_Nav_Saving", Culture) ?? "Settings_Nav_Saving";

    /// <summary>Clipboard</summary>
    public static string Settings_Nav_Clipboard => Manager.GetString("Settings_Nav_Clipboard", Culture) ?? "Settings_Nav_Clipboard";

    /// <summary>History</summary>
    public static string Settings_Nav_History => Manager.GetString("Settings_Nav_History", Culture) ?? "Settings_Nav_History";

    /// <summary>Appearance</summary>
    public static string Settings_Nav_Appearance => Manager.GetString("Settings_Nav_Appearance", Culture) ?? "Settings_Nav_Appearance";

    /// <summary>System</summary>
    public static string Settings_Nav_System => Manager.GetString("Settings_Nav_System", Culture) ?? "Settings_Nav_System";

    /// <summary>Language</summary>
    public static string Settings_Nav_Language => Manager.GetString("Settings_Nav_Language", Culture) ?? "Settings_Nav_Language";

    /// <summary>Click a field and press the keys you want. Backspace clears a shortcut.</summary>
    public static string Settings_Hotkeys_Help => Manager.GetString("Settings_Hotkeys_Help", Culture) ?? "Settings_Hotkeys_Help";

    /// <summary>Capture</summary>
    public static string Settings_Hotkey_Capture => Manager.GetString("Settings_Hotkey_Capture", Culture) ?? "Settings_Hotkey_Capture";

    /// <summary>Quick copy</summary>
    public static string Settings_Hotkey_QuickCopy => Manager.GetString("Settings_Hotkey_QuickCopy", Culture) ?? "Settings_Hotkey_QuickCopy";

    /// <summary>Select a region and release the mouse - it goes straight to the clipboard, no editing panel.</summary>
    public static string Settings_Hotkey_QuickCopyHelp => Manager.GetString("Settings_Hotkey_QuickCopyHelp", Culture) ?? "Settings_Hotkey_QuickCopyHelp";

    /// <summary>Copy full screen</summary>
    public static string Settings_Hotkey_FullScreen => Manager.GetString("Settings_Hotkey_FullScreen", Culture) ?? "Settings_Hotkey_FullScreen";

    /// <summary>Copies the monitor under the cursor to the clipboard at once, without a selection.</summary>
    public static string Settings_Hotkey_FullScreenHelp => Manager.GetString("Settings_Hotkey_FullScreenHelp", Culture) ?? "Settings_Hotkey_FullScreenHelp";

    /// <summary>Open history</summary>
    public static string Settings_Hotkey_History => Manager.GetString("Settings_Hotkey_History", Culture) ?? "Settings_Hotkey_History";

    /// <summary>Press a key combination…</summary>
    public static string Settings_Hotkey_Listening => Manager.GetString("Settings_Hotkey_Listening", Culture) ?? "Settings_Hotkey_Listening";

    /// <summary>Enable history first</summary>
    public static string Settings_Hotkey_EnableHistoryFirst => Manager.GetString("Settings_Hotkey_EnableHistoryFirst", Culture) ?? "Settings_Hotkey_EnableHistoryFirst";

    /// <summary>Ask where to save</summary>
    public static string Settings_Saving_Ask => Manager.GetString("Settings_Saving_Ask", Culture) ?? "Settings_Saving_Ask";

    /// <summary>Show a dialog on each save</summary>
    public static string Settings_Saving_AskHelp => Manager.GetString("Settings_Saving_AskHelp", Culture) ?? "Settings_Saving_AskHelp";

    /// <summary>Default folder</summary>
    public static string Settings_Saving_Folder => Manager.GetString("Settings_Saving_Folder", Culture) ?? "Settings_Saving_Folder";

    /// <summary>(default)</summary>
    public static string Settings_Saving_FolderDefaultSuffix => Manager.GetString("Settings_Saving_FolderDefaultSuffix", Culture) ?? "Settings_Saving_FolderDefaultSuffix";

    /// <summary>Choose default folder</summary>
    public static string Settings_Saving_FolderDialogTitle => Manager.GetString("Settings_Saving_FolderDialogTitle", Culture) ?? "Settings_Saving_FolderDialogTitle";

    /// <summary>Default format</summary>
    public static string Settings_Saving_Format => Manager.GetString("Settings_Saving_Format", Culture) ?? "Settings_Saving_Format";

    /// <summary>Copy to clipboard when saving</summary>
    public static string Settings_Clipboard_CopyOnSave => Manager.GetString("Settings_Clipboard_CopyOnSave", Culture) ?? "Settings_Clipboard_CopyOnSave";

    /// <summary>Keep a copy in the clipboard after saving to a file</summary>
    public static string Settings_Clipboard_CopyOnSaveHelp => Manager.GetString("Settings_Clipboard_CopyOnSaveHelp", Culture) ?? "Settings_Clipboard_CopyOnSaveHelp";

    /// <summary>Keep recent screenshots</summary>
    public static string Settings_History_Keep => Manager.GetString("Settings_History_Keep", Culture) ?? "Settings_History_Keep";

    /// <summary>Every capture is auto-archived; older files are deleted, and recent ones show in the tray History menu.</summary>
    public static string Settings_History_KeepHelp => Manager.GetString("Settings_History_KeepHelp", Culture) ?? "Settings_History_KeepHelp";

    /// <summary>Auto-delete after</summary>
    public static string Settings_History_AutoDelete => Manager.GetString("Settings_History_AutoDelete", Culture) ?? "Settings_History_AutoDelete";

    /// <summary>Off</summary>
    public static string Settings_History_Off => Manager.GetString("Settings_History_Off", Culture) ?? "Settings_History_Off";

    /// <summary>1 day</summary>
    public static string Settings_History_1Day => Manager.GetString("Settings_History_1Day", Culture) ?? "Settings_History_1Day";

    /// <summary>3 days</summary>
    public static string Settings_History_3Days => Manager.GetString("Settings_History_3Days", Culture) ?? "Settings_History_3Days";

    /// <summary>7 days</summary>
    public static string Settings_History_7Days => Manager.GetString("Settings_History_7Days", Culture) ?? "Settings_History_7Days";

    /// <summary>Accent color</summary>
    public static string Settings_Appearance_Accent => Manager.GetString("Settings_Appearance_Accent", Culture) ?? "Settings_Appearance_Accent";

    /// <summary>Start with Windows</summary>
    public static string Settings_System_AutoStart => Manager.GetString("Settings_System_AutoStart", Culture) ?? "Settings_System_AutoStart";

    /// <summary>Launch iPrtSc automatically at sign-in</summary>
    public static string Settings_System_AutoStartHelp => Manager.GetString("Settings_System_AutoStartHelp", Culture) ?? "Settings_System_AutoStartHelp";

    /// <summary>Interface language</summary>
    public static string Settings_Language_Label => Manager.GetString("Settings_Language_Label", Culture) ?? "Settings_Language_Label";

    /// <summary>Applies after you click Save.</summary>
    public static string Settings_Language_Help => Manager.GetString("Settings_Language_Help", Culture) ?? "Settings_Language_Help";

    /// <summary>Auto (system)</summary>
    public static string Settings_Language_Auto => Manager.GetString("Settings_Language_Auto", Culture) ?? "Settings_Language_Auto";

    /// <summary>Select area (C)</summary>
    public static string Overlay_Tool_Select => Manager.GetString("Overlay_Tool_Select", Culture) ?? "Overlay_Tool_Select";

    /// <summary>Move objects (V)</summary>
    public static string Overlay_Tool_Move => Manager.GetString("Overlay_Tool_Move", Culture) ?? "Overlay_Tool_Move";

    /// <summary>Pen (P)</summary>
    public static string Overlay_Tool_Pen => Manager.GetString("Overlay_Tool_Pen", Culture) ?? "Overlay_Tool_Pen";

    /// <summary>Highlighter (M)</summary>
    public static string Overlay_Tool_Marker => Manager.GetString("Overlay_Tool_Marker", Culture) ?? "Overlay_Tool_Marker";

    /// <summary>Shapes (A / L / R / E)</summary>
    public static string Overlay_Tool_Shapes => Manager.GetString("Overlay_Tool_Shapes", Culture) ?? "Overlay_Tool_Shapes";

    /// <summary>Text (T)</summary>
    public static string Overlay_Tool_Text => Manager.GetString("Overlay_Tool_Text", Culture) ?? "Overlay_Tool_Text";

    /// <summary>Numbered step (N)</summary>
    public static string Overlay_Tool_Counter => Manager.GetString("Overlay_Tool_Counter", Culture) ?? "Overlay_Tool_Counter";

    /// <summary>Stamps (S)</summary>
    public static string Overlay_Tool_Stamps => Manager.GetString("Overlay_Tool_Stamps", Culture) ?? "Overlay_Tool_Stamps";

    /// <summary>Pixelate area (B)</summary>
    public static string Overlay_Tool_Pixelate => Manager.GetString("Overlay_Tool_Pixelate", Culture) ?? "Overlay_Tool_Pixelate";

    /// <summary>Grab text (G) - drag over words, Ctrl+C to copy</summary>
    public static string Overlay_Tool_Ocr => Manager.GetString("Overlay_Tool_Ocr", Culture) ?? "Overlay_Tool_Ocr";

    /// <summary>Pick color (I) - click samples the pixel and copies its hex</summary>
    public static string Overlay_Tool_Picker => Manager.GetString("Overlay_Tool_Picker", Culture) ?? "Overlay_Tool_Picker";

    /// <summary>Color</summary>
    public static string Overlay_Tool_Color => Manager.GetString("Overlay_Tool_Color", Culture) ?? "Overlay_Tool_Color";

    /// <summary>Undo (Ctrl+Z)</summary>
    public static string Overlay_Tool_Undo => Manager.GetString("Overlay_Tool_Undo", Culture) ?? "Overlay_Tool_Undo";

    /// <summary>Redo (Ctrl+Y)</summary>
    public static string Overlay_Tool_Redo => Manager.GetString("Overlay_Tool_Redo", Culture) ?? "Overlay_Tool_Redo";

    /// <summary>Copy (Enter)</summary>
    public static string Overlay_Tool_Copy => Manager.GetString("Overlay_Tool_Copy", Culture) ?? "Overlay_Tool_Copy";

    /// <summary>Save (Ctrl+S)</summary>
    public static string Overlay_Tool_Save => Manager.GetString("Overlay_Tool_Save", Culture) ?? "Overlay_Tool_Save";

    /// <summary>Cancel (Esc)</summary>
    public static string Overlay_Tool_Cancel => Manager.GetString("Overlay_Tool_Cancel", Culture) ?? "Overlay_Tool_Cancel";

    /// <summary>Colors</summary>
    public static string Overlay_Colors_Header => Manager.GetString("Overlay_Colors_Header", Culture) ?? "Overlay_Colors_Header";

    /// <summary>Arrow (A)</summary>
    public static string Overlay_Shape_Arrow => Manager.GetString("Overlay_Shape_Arrow", Culture) ?? "Overlay_Shape_Arrow";

    /// <summary>Line (L)</summary>
    public static string Overlay_Shape_Line => Manager.GetString("Overlay_Shape_Line", Culture) ?? "Overlay_Shape_Line";

    /// <summary>Rectangle (R, Shift = square)</summary>
    public static string Overlay_Shape_Rect => Manager.GetString("Overlay_Shape_Rect", Culture) ?? "Overlay_Shape_Rect";

    /// <summary>Ellipse (E, Shift = circle)</summary>
    public static string Overlay_Shape_Ellipse => Manager.GetString("Overlay_Shape_Ellipse", Culture) ?? "Overlay_Shape_Ellipse";

    /// <summary>Stamps</summary>
    public static string Overlay_Stamps_Header => Manager.GetString("Overlay_Stamps_Header", Culture) ?? "Overlay_Stamps_Header";

    /// <summary>Ink for light backgrounds</summary>
    public static string Overlay_Stamps_InkLight => Manager.GetString("Overlay_Stamps_InkLight", Culture) ?? "Overlay_Stamps_InkLight";

    /// <summary>Ink for dark backgrounds</summary>
    public static string Overlay_Stamps_InkDark => Manager.GetString("Overlay_Stamps_InkDark", Culture) ?? "Overlay_Stamps_InkDark";

    /// <summary>Auto - ink adapts to the background under the stamp</summary>
    public static string Overlay_Stamps_InkAuto => Manager.GetString("Overlay_Stamps_InkAuto", Culture) ?? "Overlay_Stamps_InkAuto";

    /// <summary>Copied</summary>
    public static string Overlay_Copied => Manager.GetString("Overlay_Copied", Culture) ?? "Overlay_Copied";

    /// <summary>No text found in selection</summary>
    public static string Overlay_Hint_NoText => Manager.GetString("Overlay_Hint_NoText", Culture) ?? "Overlay_Hint_NoText";

    /// <summary>Recognizing text…</summary>
    public static string Overlay_Hint_Recognizing => Manager.GetString("Overlay_Hint_Recognizing", Culture) ?? "Overlay_Hint_Recognizing";

    /// <summary>Text recognition failed</summary>
    public static string Overlay_Hint_OcrFailed => Manager.GetString("Overlay_Hint_OcrFailed", Culture) ?? "Overlay_Hint_OcrFailed";

    /// <summary>{0} copied</summary>
    public static string Overlay_Hint_ColorCopied => Manager.GetString("Overlay_Hint_ColorCopied", Culture) ?? "Overlay_Hint_ColorCopied";

    /// <summary>Copy text</summary>
    public static string Overlay_Menu_CopyText => Manager.GetString("Overlay_Menu_CopyText", Culture) ?? "Overlay_Menu_CopyText";

    /// <summary>Select full screen</summary>
    public static string Overlay_Menu_SelectFullScreen => Manager.GetString("Overlay_Menu_SelectFullScreen", Culture) ?? "Overlay_Menu_SelectFullScreen";

    /// <summary>Clear selection</summary>
    public static string Overlay_Menu_ClearSelection => Manager.GetString("Overlay_Menu_ClearSelection", Culture) ?? "Overlay_Menu_ClearSelection";

    /// <summary>Save screenshot</summary>
    public static string Overlay_SaveDialog_Title => Manager.GetString("Overlay_SaveDialog_Title", Culture) ?? "Overlay_SaveDialog_Title";

    /// <summary>PNG image</summary>
    public static string Overlay_SaveDialog_Png => Manager.GetString("Overlay_SaveDialog_Png", Culture) ?? "Overlay_SaveDialog_Png";

    /// <summary>JPEG image</summary>
    public static string Overlay_SaveDialog_Jpeg => Manager.GetString("Overlay_SaveDialog_Jpeg", Culture) ?? "Overlay_SaveDialog_Jpeg";

    /// <summary>Capture</summary>
    public static string Tray_Menu_Capture => Manager.GetString("Tray_Menu_Capture", Culture) ?? "Tray_Menu_Capture";

    /// <summary>Quick copy</summary>
    public static string Tray_Menu_QuickCopy => Manager.GetString("Tray_Menu_QuickCopy", Culture) ?? "Tray_Menu_QuickCopy";

    /// <summary>History…</summary>
    public static string Tray_Menu_History => Manager.GetString("Tray_Menu_History", Culture) ?? "Tray_Menu_History";

    /// <summary>Settings…</summary>
    public static string Tray_Menu_Settings => Manager.GetString("Tray_Menu_Settings", Culture) ?? "Tray_Menu_Settings";

    /// <summary>About</summary>
    public static string Tray_Menu_About => Manager.GetString("Tray_Menu_About", Culture) ?? "Tray_Menu_About";

    /// <summary>Exit</summary>
    public static string Tray_Menu_Exit => Manager.GetString("Tray_Menu_Exit", Culture) ?? "Tray_Menu_Exit";

    /// <summary>Download update v{0}</summary>
    public static string Tray_Menu_Update => Manager.GetString("Tray_Menu_Update", Culture) ?? "Tray_Menu_Update";

    /// <summary>iPrtSc v{0}</summary>
    public static string Tray_Tooltip => Manager.GetString("Tray_Tooltip", Culture) ?? "Tray_Tooltip";

    /// <summary>iPrtSc v{0} - update {1} available</summary>
    public static string Tray_TooltipUpdate => Manager.GetString("Tray_TooltipUpdate", Culture) ?? "Tray_TooltipUpdate";

    /// <summary>Could not register the hotkey &quot;{0}&quot; - it may be in use by another app.</summary>
    public static string Balloon_HotkeyFailed => Manager.GetString("Balloon_HotkeyFailed", Culture) ?? "Balloon_HotkeyFailed";

    /// <summary>Print Screen now opens iPrtSc. Windows&apos; Snipping Tool shortcut was turned off - re-enable it any time under Settings ▸ Bluetooth &amp; devices ▸ Keyboard, or just pick a different hotkey here.</summary>
    public static string Balloon_PrtScClaimed => Manager.GetString("Balloon_PrtScClaimed", Culture) ?? "Balloon_PrtScClaimed";

    /// <summary>Print Screen released - Windows&apos; Snipping Tool shortcut was restored.</summary>
    public static string Balloon_PrtScReleased => Manager.GetString("Balloon_PrtScReleased", Culture) ?? "Balloon_PrtScReleased";

    /// <summary>Version {0} is available. Right-click the tray icon to download.</summary>
    public static string Balloon_UpdateAvailable => Manager.GetString("Balloon_UpdateAvailable", Culture) ?? "Balloon_UpdateAvailable";

    /// <summary>Screen copied to clipboard</summary>
    public static string Balloon_ScreenCopied => Manager.GetString("Balloon_ScreenCopied", Culture) ?? "Balloon_ScreenCopied";

    /// <summary>Saved: {0}</summary>
    public static string Balloon_Saved => Manager.GetString("Balloon_Saved", Culture) ?? "Balloon_Saved";

    /// <summary>Text copied to clipboard</summary>
    public static string Balloon_TextCopied => Manager.GetString("Balloon_TextCopied", Culture) ?? "Balloon_TextCopied";

    /// <summary>Recent screenshots</summary>
    public static string History_Title => Manager.GetString("History_Title", Culture) ?? "History_Title";

    /// <summary>Keep this window open</summary>
    public static string History_Pin => Manager.GetString("History_Pin", Culture) ?? "History_Pin";

    /// <summary>No screenshots yet</summary>
    public static string History_Empty => Manager.GetString("History_Empty", Culture) ?? "History_Empty";

    /// <summary>Left-click: copy  ·  Right-click: open</summary>
    public static string History_ClickHint => Manager.GetString("History_ClickHint", Culture) ?? "History_ClickHint";

    /// <summary>Open history folder</summary>
    public static string History_OpenFolder => Manager.GetString("History_OpenFolder", Culture) ?? "History_OpenFolder";

    /// <summary>Copied</summary>
    public static string History_Flash_Copied => Manager.GetString("History_Flash_Copied", Culture) ?? "History_Flash_Copied";

    /// <summary>Opened</summary>
    public static string History_Flash_Opened => Manager.GetString("History_Flash_Opened", Culture) ?? "History_Flash_Opened";

    /// <summary>Copy failed</summary>
    public static string History_Flash_CopyFailed => Manager.GetString("History_Flash_CopyFailed", Culture) ?? "History_Flash_CopyFailed";

    /// <summary>Open failed</summary>
    public static string History_Flash_OpenFailed => Manager.GetString("History_Flash_OpenFailed", Culture) ?? "History_Flash_OpenFailed";

    /// <summary>About iPrtSc</summary>
    public static string About_WindowTitle => Manager.GetString("About_WindowTitle", Culture) ?? "About_WindowTitle";

    /// <summary>Version {0}</summary>
    public static string About_Version => Manager.GetString("About_Version", Culture) ?? "About_Version";

    /// <summary>Screenshots that do more than screenshots.</summary>
    public static string About_Tagline => Manager.GetString("About_Tagline", Culture) ?? "About_Tagline";

    /// <summary>Update available: v{0} - Download</summary>
    public static string About_UpdateBanner => Manager.GetString("About_UpdateBanner", Culture) ?? "About_UpdateBanner";

    /// <summary>Contact:</summary>
    public static string About_Contact => Manager.GetString("About_Contact", Culture) ?? "About_Contact";

    /// <summary>iPrtSc on GitHub</summary>
    public static string About_GitHub => Manager.GetString("About_GitHub", Culture) ?? "About_GitHub";

    /// <summary>Buy me a coffee ☕</summary>
    public static string About_Coffee => Manager.GetString("About_Coffee", Culture) ?? "About_Coffee";
}
