# Regenerates src\iPrtSc\Resources\Strings.Designer.cs from Strings.resx (the English
# source of truth). Run it after adding or removing a key; check-locales.ps1 fails if the
# committed designer is out of sync.
#
# Usage (from anywhere):  .\tools\gen-strings.ps1

$ErrorActionPreference = 'Stop'
$repoRoot = Split-Path -Parent $PSScriptRoot
$dir = Join-Path $repoRoot 'src\iPrtSc\Resources'
$resx = Join-Path $dir 'Strings.resx'
$out = Join-Path $dir 'Strings.Designer.cs'

[xml]$doc = Get-Content -LiteralPath $resx -Encoding UTF8
$nl = "`r`n"

$sb = New-Object System.Text.StringBuilder
[void]$sb.Append("// <auto-generated>$nl")
[void]$sb.Append("//     Generated by tools\gen-strings.ps1 from Strings.resx. Do not edit by hand.$nl")
[void]$sb.Append("// </auto-generated>$nl$nl")
[void]$sb.Append("#nullable enable$nl$nl")
[void]$sb.Append("using System.Globalization;$nl")
[void]$sb.Append("using System.Resources;$nl$nl")
[void]$sb.Append("namespace iPrtSc.Resources;$nl$nl")
[void]$sb.Append("/// <summary>Strongly-typed access to the UI strings (Strings.resx + per-culture Strings.xx.resx).</summary>$nl")
[void]$sb.Append("public static class Strings$nl{$nl")
[void]$sb.Append("    private static readonly ResourceManager Manager =$nl")
[void]$sb.Append("        new(`"iPrtSc.Resources.Strings`", typeof(Strings).Assembly);$nl$nl")
[void]$sb.Append("    /// <summary>Overrides the culture used for lookups; null follows CurrentUICulture.</summary>$nl")
[void]$sb.Append("    public static CultureInfo? Culture { get; set; }$nl")

foreach ($d in $doc.root.data) {
    $name = $d.name
    $text = ($d.value -replace '[\r\n]+', ' ')
    $text = [System.Security.SecurityElement]::Escape($text)
    [void]$sb.Append($nl)
    [void]$sb.Append("    /// <summary>$text</summary>$nl")
    [void]$sb.Append("    public static string $name => Manager.GetString(`"$name`", Culture) ?? `"$name`";$nl")
}
[void]$sb.Append("}$nl")

[System.IO.File]::WriteAllText($out, $sb.ToString(), (New-Object System.Text.UTF8Encoding($false)))
Write-Host "Wrote $out ($(@($doc.root.data).Count) keys)"
